pygments: true
auto: true
permalink: /:year/:month/:day/:title/
markdown: redcarpet2
redcarpet:
  extensions: ["fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "lax_html_blocks", "hard_wrap", "tables", "xhtml"]
safe: false
baseurl: http://madhums.me
lsi: false
