name: madhums
description: "writings, ramblings, code and others"
meta_description: "writings, ramblings, code and others"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://madhums.me'
google_analytics: 'UA-32621427-1'
disqus: false
disqus_shortname: 'madhums'

# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'Madhusudhan Srinivasa'
authorTwitter:  'madhums'

permalink:       /:year/:month/:day/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
